"""add reports table

Revision ID: 80126bccb7c4
Revises: 926d27b15553
Create Date: 2026-09-12 02:38:24.056934

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '80126bccb7c4'
down_revision: Union[str, None] = '926d27b15553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('template_version', sa.String(length=30), nullable=False),
    sa.Column('include_scope3', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_reports_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_reports_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
