"""initial schema

Revision ID: 926d27b15553
Revises: 
Create Date: 2026-09-12 02:32:46.617476

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '926d27b15553'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('circular_interventions',
    sa.Column('intervention_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('process_category', sa.String(length=100), nullable=True),
    sa.Column('current_practice', sa.Text(), nullable=True),
    sa.Column('alternative_practice', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('max_capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('expected_co2_reduction_min_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('expected_co2_reduction_max_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('energy_reduction_min_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('energy_reduction_max_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('waste_reduction_min_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('waste_reduction_max_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('implementation_months_min', sa.Integer(), nullable=True),
    sa.Column('implementation_months_max', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("complexity IS NULL OR complexity IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_circular_interventions_complexity_valid')),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_circular_interventions_risk_level_valid')),
    sa.CheckConstraint('expected_co2_reduction_min_pct IS NULL OR expected_co2_reduction_max_pct IS NULL OR expected_co2_reduction_max_pct >= expected_co2_reduction_min_pct', name=op.f('ck_circular_interventions_co2_reduction_range')),
    sa.CheckConstraint('min_capex IS NULL OR max_capex IS NULL OR max_capex >= min_capex', name=op.f('ck_circular_interventions_capex_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circular_interventions')),
    sa.UniqueConstraint('intervention_code', name=op.f('uq_circular_interventions_intervention_code'))
    )
    op.create_table('emission_factors',
    sa.Column('factor_code', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('region_country', sa.String(length=100), nullable=True),
    sa.Column('region_state', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('input_unit', sa.String(length=30), nullable=False),
    sa.Column('output_unit', sa.String(length=30), nullable=False),
    sa.Column('co2_factor', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ch4_factor', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('n2o_factor', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_co2e_factor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=True),
    sa.Column('supplier_specific', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence_level IS NULL OR confidence_level IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_emission_factors_confidence_level_valid')),
    sa.CheckConstraint("scope IN ('SCOPE_1', 'SCOPE_2', 'SCOPE_3')", name=op.f('ck_emission_factors_scope_valid')),
    sa.CheckConstraint('ch4_factor >= 0', name=op.f('ck_emission_factors_ch4_factor_nonnegative')),
    sa.CheckConstraint('co2_factor >= 0', name=op.f('ck_emission_factors_co2_factor_nonnegative')),
    sa.CheckConstraint('n2o_factor >= 0', name=op.f('ck_emission_factors_n2o_factor_nonnegative')),
    sa.CheckConstraint('source_year >= 1900 AND source_year <= 2100', name=op.f('ck_emission_factors_source_year_range')),
    sa.CheckConstraint('total_co2e_factor >= 0', name=op.f('ck_emission_factors_total_factor_nonnegative')),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from', name=op.f('ck_emission_factors_valid_dates_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factors')),
    sa.UniqueConstraint('factor_code', name=op.f('uq_emission_factors_factor_code'))
    )
    op.create_index('idx_emission_factor_lookup', 'emission_factors', ['category', 'subcategory', 'region_country', 'active'], unique=False)
    op.create_table('energy_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('renewable', sa.Boolean(), nullable=True),
    sa.Column('standard_unit', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_sources'))
    )
    op.create_table('industry_benchmarks',
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('process_category', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('p25', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('median', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('p75', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_benchmarks'))
    )
    op.create_table('materials',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('standard_unit', sa.String(length=30), nullable=True),
    sa.Column('recyclable', sa.Boolean(), nullable=True),
    sa.Column('renewable_material', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry_sector', sa.String(length=100), nullable=False),
    sa.Column('industry_subtype', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('organization_size', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("organization_size IN ('SMALL', 'MEDIUM')", name=op.f('ck_organizations_organization_size_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('waste_types',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('hazardous', sa.Boolean(), nullable=True),
    sa.Column('recyclable', sa.Boolean(), nullable=True),
    sa.Column('standard_unit', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_types'))
    )
    op.create_table('facilities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('annual_production', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('production_unit', sa.String(length=30), nullable=True),
    sa.Column('working_days_per_year', sa.Integer(), nullable=True),
    sa.Column('working_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('annual_production >= 0', name=op.f('ck_facilities_production_nonnegative')),
    sa.CheckConstraint('working_days_per_year >= 0 AND working_days_per_year <= 366', name=op.f('ck_facilities_working_days_range')),
    sa.CheckConstraint('working_hours_per_day >= 0 AND working_hours_per_day <= 24', name=op.f('ck_facilities_working_hours_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_facilities_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities')),
    sa.UniqueConstraint('organization_id', 'facility_code', name='uq_org_facility_code')
    )
    op.create_table('intervention_applicability',
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('applicability_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['circular_interventions.id'], name=op.f('fk_intervention_applicability_intervention_id_circular_interventions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention_applicability'))
    )
    op.create_table('processes',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process_category', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence_no > 0', name=op.f('ck_processes_sequence_positive')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_processes_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes'))
    )
    op.create_table('reporting_periods',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_reporting_periods_end_after_start')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_reporting_periods_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporting_periods'))
    )
    op.create_table('carbon_inventory_summary',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('scope1_kgco2e', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('scope2_kgco2e', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('scope3_kgco2e', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_kgco2e', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('carbon_intensity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('production_unit', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_carbon_inventory_summary_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_carbon_inventory_summary_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_inventory_summary'))
    )
    op.create_table('circularity_scores',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('recycled_input_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waste_recovery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('energy_recovery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('water_reuse_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reuse_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('methodology_version', sa.String(length=30), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_circularity_scores_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_circularity_scores_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circularity_scores'))
    )
    op.create_table('data_quality_assessments',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('factor_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temporal_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unit_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_data_quality_assessments_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_data_quality_assessments_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_assessments'))
    )
    op.create_table('ingestion_batches',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('accepted_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_ingestion_batches_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_ingestion_batches_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_batches')),
    sa.UniqueConstraint('import_id', name=op.f('uq_ingestion_batches_import_id'))
    )
    op.create_table('process_assets',
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('asset_name', sa.String(length=150), nullable=True),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('rated_capacity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('capacity_unit', sa.String(length=30), nullable=True),
    sa.Column('operating_hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_process_assets_process_id_processes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_assets'))
    )
    op.create_table('process_links',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('source_process_id', sa.Uuid(), nullable=False),
    sa.Column('target_process_id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('source_process_id <> target_process_id', name=op.f('ck_process_links_no_self_loop')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_process_links_facility_id_facilities')),
    sa.ForeignKeyConstraint(['source_process_id'], ['processes.id'], name=op.f('fk_process_links_source_process_id_processes')),
    sa.ForeignKeyConstraint(['target_process_id'], ['processes.id'], name=op.f('fk_process_links_target_process_id_processes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_links'))
    )
    op.create_table('scenarios',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scenario_type', sa.String(length=30), nullable=True),
    sa.Column('budget_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('target_reduction_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('budget_limit >= 0', name=op.f('ck_scenarios_budget_nonnegative')),
    sa.CheckConstraint('target_reduction_pct >= 0 AND target_reduction_pct <= 100', name=op.f('ck_scenarios_target_reduction_range')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_scenarios_facility_id_facilities')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_scenarios_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_table('activity_data',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('activity_category', sa.String(length=40), nullable=False),
    sa.Column('activity_subcategory', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('original_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('original_unit', sa.String(length=30), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('normalized_unit', sa.String(length=30), nullable=False),
    sa.Column('data_source_type', sa.String(length=30), nullable=False),
    sa.Column('measured_or_estimated', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('carbon_data_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("activity_category IN ('ELECTRICITY', 'FUEL', 'MATERIAL', 'WATER', 'TRANSPORT', 'WASTE', 'REFRIGERANT', 'STEAM', 'OTHER')", name=op.f('ck_activity_data_activity_category_valid')),
    sa.CheckConstraint("data_source_type IN ('MANUAL', 'CSV', 'EXCEL', 'API', 'SENSOR', 'OCR')", name=op.f('ck_activity_data_data_source_type_valid')),
    sa.CheckConstraint("measured_or_estimated IN ('MEASURED', 'ESTIMATED')", name=op.f('ck_activity_data_measured_or_estimated_valid')),
    sa.CheckConstraint('carbon_data_quality_score >= 0 AND carbon_data_quality_score <= 100', name=op.f('ck_activity_data_carbon_dq_range')),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name=op.f('ck_activity_data_confidence_range')),
    sa.CheckConstraint('normalized_value >= 0', name=op.f('ck_activity_data_normalized_value_nonnegative')),
    sa.CheckConstraint('original_value >= 0', name=op.f('ck_activity_data_original_value_nonnegative')),
    sa.ForeignKeyConstraint(['asset_id'], ['process_assets.id'], name=op.f('fk_activity_data_asset_id_process_assets')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_activity_data_facility_id_facilities')),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_activity_data_process_id_processes')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_activity_data_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_data'))
    )
    op.create_index('idx_activity_facility_period', 'activity_data', ['facility_id', 'reporting_period_id'], unique=False)
    op.create_index('idx_activity_process', 'activity_data', ['process_id'], unique=False)
    op.create_index('uq_activity_source_row', 'activity_data', ['facility_id', 'reporting_period_id', 'source_row_hash'], unique=True, postgresql_where=None)
    op.create_table('emission_hotspots',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('hotspot_type', sa.String(length=30), nullable=True),
    sa.Column('emissions_kgco2e', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('contribution_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('carbon_intensity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('inefficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waste_ratio_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('improvement_potential_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hotspot_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['process_assets.id'], name=op.f('fk_emission_hotspots_asset_id_process_assets')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_emission_hotspots_facility_id_facilities')),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_emission_hotspots_process_id_processes')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_emission_hotspots_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_hotspots'))
    )
    op.create_index('idx_hotspot_facility_period', 'emission_hotspots', ['facility_id', 'reporting_period_id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], name=op.f('fk_ingestion_errors_batch_id_ingestion_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_errors'))
    )
    op.create_table('scenario_results',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_emissions_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('projected_emissions_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_co2_saving_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('reduction_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('annual_saving', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('payback_years', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_results_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_results'))
    )
    op.create_table('anomaly_results',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('activity_data_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_note', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_data_id'], ['activity_data.id'], name=op.f('fk_anomaly_results_activity_data_id_activity_data')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_anomaly_results_facility_id_facilities')),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_anomaly_results_process_id_processes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_results'))
    )
    op.create_table('emission_calculations',
    sa.Column('activity_data_id', sa.Uuid(), nullable=False),
    sa.Column('emission_factor_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_version', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('co2e_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_data_id'], ['activity_data.id'], name=op.f('fk_emission_calculations_activity_data_id_activity_data')),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], name=op.f('fk_emission_calculations_emission_factor_id_emission_factors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_calculations'))
    )
    op.create_index('idx_emission_calc_activity', 'emission_calculations', ['activity_data_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('hotspot_id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('carbon_saving_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('financial_return_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feasibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('circularity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('implementation_speed_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_recommendations_facility_id_facilities')),
    sa.ForeignKeyConstraint(['hotspot_id'], ['emission_hotspots.id'], name=op.f('fk_recommendations_hotspot_id_emission_hotspots')),
    sa.ForeignKeyConstraint(['intervention_id'], ['circular_interventions.id'], name=op.f('fk_recommendations_intervention_id_circular_interventions')),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], name=op.f('fk_recommendations_reporting_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('idx_recommendation_facility', 'recommendations', ['facility_id', 'reporting_period_id'], unique=False)
    op.create_table('recommendation_assessments',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_annual_opex_change', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_annual_saving', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('estimated_co2_saving_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('estimated_energy_saving', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('estimated_waste_reduction', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('payback_years', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_tonne_co2_avoided', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_assessments_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_assessments'))
    )
    op.create_table('recommendation_feedback',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actual_capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_annual_saving', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_co2_saving_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_feedback_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedback'))
    )
    op.create_table('scenario_interventions',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('adoption_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('adoption_percentage >= 0 AND adoption_percentage <= 100', name=op.f('ck_scenario_interventions_adoption_range')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_scenario_interventions_recommendation_id_recommendations')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_interventions_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_interventions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_interventions')
    op.drop_table('recommendation_feedback')
    op.drop_table('recommendation_assessments')
    op.drop_index('idx_recommendation_facility', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_emission_calc_activity', table_name='emission_calculations')
    op.drop_table('emission_calculations')
    op.drop_table('anomaly_results')
    op.drop_table('scenario_results')
    op.drop_table('ingestion_errors')
    op.drop_index('idx_hotspot_facility_period', table_name='emission_hotspots')
    op.drop_table('emission_hotspots')
    op.drop_index('uq_activity_source_row', table_name='activity_data', postgresql_where=None)
    op.drop_index('idx_activity_process', table_name='activity_data')
    op.drop_index('idx_activity_facility_period', table_name='activity_data')
    op.drop_table('activity_data')
    op.drop_table('scenarios')
    op.drop_table('process_links')
    op.drop_table('process_assets')
    op.drop_table('ingestion_batches')
    op.drop_table('data_quality_assessments')
    op.drop_table('circularity_scores')
    op.drop_table('carbon_inventory_summary')
    op.drop_table('reporting_periods')
    op.drop_table('processes')
    op.drop_table('intervention_applicability')
    op.drop_table('facilities')
    op.drop_table('waste_types')
    op.drop_table('organizations')
    op.drop_table('materials')
    op.drop_table('industry_benchmarks')
    op.drop_table('energy_sources')
    op.drop_index('idx_emission_factor_lookup', table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_table('circular_interventions')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
